name: "Deploy"
on:
  push:
    branches:
      - master
  schedule:
    - cron: '18 7 */5 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: bin-calendar

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Build .ics file
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 generate_ics.py

        env:
          OUTPUT_FILENAME: index.html
          SOURCE_URL: ${{ secrets.SOURCE_URL }}

      - name: 'Tar files'
        run: mkdir -p output && tar -czvf output/build.tar.gz ./index.html

      - name: Archive calendar file
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          name: github-pages
          path: output/
          retention-days: 14

  deploy:
    needs: build

    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
