name: "Deploy"
on:
  push:
    branches:
      - master
  schedule:
    - cron: '18 7 */5 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: bin-calendar

    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Build .ics file
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
          python3 generate_ics.py

        env:
          OUTPUT_FILENAME: index.md
          SOURCE_URL: ${{ secrets.SOURCE_URL }}

      - name: Archive calendar file
        uses: actions/upload-artifact@v4
        with:
          name: bin-calendar
          path: bin-calendar.ics
          if-no-files-found: error
          compression-level: 9
          retention-days: 14

  deploy:
    needs: build

    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    steps:
      - name: Configure Pages
        uses: actions/configure-pages@v4

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: bin-calendar
